import img1 from '@static/yinyang/1.png'
import img2 from '@static/yinyang/2.png'
import img3 from '@static/yinyang/3.png'
import img4 from '@static/yinyang/4.png'
import headuserbg from '@static/yinyang/headuserbg.png'
import headbg from '@static/yinyang/headbg.png'
import cardtop from '@static/yinyang/cardtop.png'
import cry from '@static/yinyang/cry.png'
import tips from '@static/yinyang/tips.png'
import cardbottom from '@static/yinyang/cardbottom.png'
import qicon from '@static/yinyang/qicon.png'
import smile from '@static/yinyang/smile.png'
import yy_topbg from '@static/yinyang/yy_topbg.png'
import planbg from '@static/yinyang/planbg.png'
import phone from '@static/yinyang/phone.png'
import shareHeader from '@static/yinyang/shareHeader.png'
import toshareIcon from '@static/yinyang/toshareIcon.png'
import toshareIcon1 from '@static/yinyang/toshareIcon1.png'
import closeMask from '@static/yinyang/closeMask.png'
import selected from '@static/yinyang/selected.png'
import nfriend_share from '@static/yinyang/nfriend_share.png'
import manicon1 from '@static/yinyang/manicon1.png'
import manicon2 from '@static/yinyang/manicon2.png'
import manicon3 from '@static/yinyang/manicon3.png'
import manicon4 from '@static/yinyang/manicon4.png'
import manicon5 from '@static/yinyang/manicon5.png'
import manicon6 from '@static/yinyang/manicon6.png'

export default {
  img1,img2,img3,img4,headuserbg,headbg,cry,cardbottom,tips,cardtop,qicon,smile,yy_topbg,phone,planbg,shareHeader,
  toshareIcon, toshareIcon1, closeMask, selected, nfriend_share, manicon1,manicon2, manicon3, manicon4, manicon5,manicon6,
}
